// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;

namespace MarketplaceWorker.Adapters.Repository.Context;

public partial class MarketplaceWorkerDBContext : DbContext
{
    public MarketplaceWorkerDBContext(DbContextOptions<MarketplaceWorkerDBContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       //Inclua aqui as configurações das entidades da base
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}