// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using TemplateHexagonal.Core.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace TemplateHexagonal.Adapters.Repository.Context;

public partial class TemplateHexagonalDBContext : DbContext
{
    public TemplateHexagonalDBContext(DbContextOptions<TemplateHexagonalDBContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       //Inclua aqui as configurações das entidades da base
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}