// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HexagonalAPIWEBWORKER.Core.Domain.Models;

public partial class Agency
{
    public int Id { get; set; }

    public string Name { get; set; }

    public Guid SubscriptionId { get; set; }

    public string DocumentNumber { get; set; }

    public DateTime CreateDate { get; set; }

    public bool Active { get; set; }

    public string DocumentCode { get; set; }

}