// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using HexagonalAPIWEBWORKER.Core.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace HexagonalAPIWEBWORKER.Adapters.Repository.Context;

public partial class HexagonalAPIWEBWORKERDBContext : DbContext
{
    public HexagonalAPIWEBWORKERDBContext(DbContextOptions<HexagonalAPIWEBWORKERDBContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
       //Inclua aqui as configurações das entidades da base
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}