// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TemplateHexagonal.Adapters.Repository.Models;

public partial class Agency
{
    public int Id { get; set; }

    public string Name { get; set; }

    public Guid SubscriptionId { get; set; }

    public string DocumentNumber { get; set; }

    public DateTime CreateDate { get; set; }

    public bool Active { get; set; }

    public string DocumentCode { get; set; }

    public virtual ICollection<Bidding> Biddings { get; set; } = new List<Bidding>();

    public virtual ICollection<Commitment> Commitments { get; set; } = new List<Commitment>();

    public virtual ICollection<SearchConfig> SearchConfigs { get; set; } = new List<SearchConfig>();
}